config/routes.rb
Rails.application.routes.draw do
  get 'users/cancel' => 'users#cancel'
  devise_for :users
  resources :users, only: [ :show ]
  post 'users/:id' => 'users#update'
  get 'scenario' => 'scenarios#show'
  get 'scenario/:page' => 'scenarios#show'
  resources :characters, only: [ :index, :show, :new, :create ]

  root 'static#home'
  get 'about' => 'static#about'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Chronicle</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">chroniclr</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="<%='active' if current_page?(root_path)%>"><%=link_to "Home", root_path %></li>
					<li class="<%='active' if current_page?(about_path)%>"><%=link_to "About", about_path %></li>
					<li class="<%='active' if current_page?(scenario_path)%>"><%=link_to "Scenarios", scenario_path %></li>
					<% if user_signed_in? %>
					<li class="<%='active' if current_page?(characters_path)%>"><%=link_to "Characters", characters_path %></li>
					<% end %>
				</ul>
				<ul class="nav navbar-nav navbar-right">
<% if user_signed_in? %>
					<li class="active">
						<a href="<%=url_for edit_user_registration_path%>">
							<span class="glyphicon glyphicon-user"></span> <%=current_user[ "username" ]%>
						</a>
					</li>
					<li><%=link_to "Logout", destroy_user_session_path, :method => :delete %></li>
<% else %>
					<li class="<%='active' if current_page?(new_user_registration_path)%>"><%=link_to "Sign Up", new_user_registration_path %></li>
					<li class="<%='active' if current_page?(new_user_session_path)%>"><%=link_to "Login", new_user_session_path %></li>
<% end %>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>

	<div class="container">
	<% if notice %>
		<div class="alert alert-info"><p class="notice"><%= notice %></p></div>
	<% end %>
	<% if alert %>
		<div class="alert alert-danger"><p class="alert"><%= alert %></p></div>
	<% end %>
		<%= yield %>
	</div>

</body>
</html>